# SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Nox <nebulousnox38@gmail.com>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 blobadoodle <me@bloba.dev>
# SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: NanoTrasenSpectre
  name: job-name-nanotrasen-spectre
  description: job-description-nanotrasen-spectre
  playTimeTracker: JobNanoTrasenSpectre
  setPreference: false
  startingGear: NanoTrasenSpectreGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
    # Goobstation
    - NanotrasenRepresentative
    - BlueshieldOfficer
  special: # Goobstation Start - I basically re-did all of deathsquads stuff so. - Sol
    - !type:AddImplantSpecial
      implants:
        [
          MindShieldImplant,
          FreedomImplant,
          BluespaceLifelineImplant,
          RadioImplantCentcomm,
          NutrimentPumpImplant,
          StypticStimulatorImplant,
          DeathRattleImplantCentcomm
        ]
    - !type:AddComponentSpecial
      components:
        - type: DeathSquadMember # Goobstation

  # Goobstation Start - I basically re-did all of deathsquads stuff so. - Sol
- type: startingGear
  id: NanoTrasenSpectreGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingModsuitSpectreFilled
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesGlassesDeathsquad # Goobstation
    neck: ExecutiveIDCard # Executive Access!
    ears: ClothingHeadsetDeathsquad # Goobstation
    gloves: ClothingHandsGlovesDeathsquad # Rip and TEAR
    outerClothing: ClothingOuterVestWebDurathread
    shoes: ClothingShoesBootsMagDeathsquad # These boots are cooler.
    id: DeathsquadPDA # New PDA!
    pocket1: PhoronSabre # Goobstation
    pocket2: WeaponRevolverMateba # Goobstation
    belt: ClothingBeltDeathsquadWebbingFilled # Centcomm Doesn't use syndicate tech.
  storage:
    back:
      - SpeedLoaderMatebaAP # Goobstation - 7 rounds
      - SpeedLoaderMatebaAP # Goobstation - 7 rounds
  inhand:
    - WeaponPulseRifle
    # Goobstation End
