- type: playTimeTracker
  id: JobCentCommIntern

- type: playTimeTracker
  id: JobCentCommDireggtor

- type: playTimeTracker
  id: JobNanoTrasenSpectre
  
- type: playTimeTracker
  id: JobTransitPrisoner
